const app=document.getElementById("app");let dashboard=null;let publicData=null;let booking={service:null,date:new Date().toISOString().slice(0,10),time:null,step:1};let mode="login";

const api=async(url,opt={})=>{const r=await fetch(url,{headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Something went wrong");return j};
const money=p=>(Number(p)/100).toLocaleString("en-GB",{style:"currency",currency:"GBP"});
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const initials=s=>String(s).split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();

async function start(){const me=await api("/api/auth/me");if(me.signedIn){await loadDash();return}renderAuth()}
function renderAuth(){app.innerHTML=`<div class="center"><div class="card" style="max-width:480px;width:100%"><div class="logo">praxis<i>•</i>bookings</div><h1>${mode==="login"?"Welcome back":"Create your business account"}</h1><p class="sub">${mode==="login"?"Sign in to manage your bookings.":"Set up your booking business in a few minutes."}</p>
${mode==="signup"?`<div class="field"><label>Business name</label><input id="businessName" placeholder="Northside Grooming"></div><div class="field"><label>Business type</label><input id="category" placeholder="Dog groomer"></div>`:""}
<div class="field"><label>Email</label><input id="email" type="email" placeholder="you@business.co.uk"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="At least 8 characters"></div>
<button class="btn primary" style="width:100%" onclick="${mode==="login"?"login()":"signup()"}">${mode==="login"?"Sign in":"Create account"}</button>
<p class="small" style="text-align:center;margin-top:16px">${mode==="login"?'New to Praxis? <a href="#" onclick="mode=\'signup\';renderAuth()">Create an account</a>':'Already have an account? <a href="#" onclick="mode=\'login\';renderAuth()">Sign in</a>'}</p></div></div>`}
async function login(){try{await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:email.value,password:password.value})});await loadDash()}catch(e){alert(e.message)}}
async function signup(){try{await api("/api/auth/signup",{method:"POST",body:JSON.stringify({email:email.value,password:password.value,businessName:businessName.value,category:category.value})});await loadDash()}catch(e){alert(e.message)}}
async function loadDash(){dashboard=await api("/api/dashboard");renderDash("overview")}
function nav(view){renderDash(view)}
function renderDash(view){
const b=dashboard.business, bs=dashboard.bookings, revenue=bs.filter(x=>x.payment_status==="paid").reduce((a,x)=>a+x.amount_pence,0);
app.innerHTML=`<header class="top"><div class="logo">praxis<i>•</i>bookings</div><div><button class="btn light" onclick="openPublic()">View booking page</button><button class="btn primary" onclick="logout()">Sign out</button></div></header><div class="layout"><aside class="side">
<button class="${view==="overview"?"active":""}" onclick="nav('overview')">▦ Dashboard</button><button class="${view==="bookings"?"active":""}" onclick="nav('bookings')">▤ Bookings</button><button class="${view==="calendar"?"active":""}" onclick="nav('calendar')">▦ Calendar</button><button class="${view==="services"?"active":""}" onclick="nav('services')">◈ Services</button><button class="${view==="staff"?"active":""}" onclick="nav('staff')">● Staff</button><button class="${view==="availability"?"active":""}" onclick="nav('availability')">◷ Availability</button><button class="${view==="settings"?"active":""}" onclick="nav('settings')">⚙ Settings</button></aside><main class="main">${content(view,b,revenue,bs)}</main></div>`}
function head(k,t,s,a=""){return `<div class="head"><div><div class="eyebrow">${k}</div><h1 class="title">${t}</h1><p class="sub">${s}</p></div><div class="actions">${a}</div></div>`}
function content(v,b,revenue,bs){
if(v==="overview")return head("Dashboard","Good evening 👋","Your business at a glance.",`<button class="btn primary" onclick="openPublic()">Open booking page</button>`) + `<div class="grid stats">${stat(bs.filter(x=>x.booking_date===new Date().toISOString().slice(0,10)).length,"Today's bookings")} ${stat(bs.filter(x=>x.status!=="cancelled").length,"Upcoming bookings")} ${stat(money(revenue),"Paid revenue")} ${stat(Math.round(bs.filter(x=>x.status==="confirmed").length/Math.max(bs.length,1)*100)+"%","Confirmation rate")}</div><div class="card" style="margin-top:18px"><h2>Recent bookings</h2>${bookingTable(bs.slice().reverse().slice(0,8))}</div>`;
if(v==="bookings")return head("Manage","Bookings","All appointments and payment statuses.",`<button class="btn primary" onclick="openPublic()">New booking</button>`)+`<div class="card">${bookingTable(bs)}</div>`;
if(v==="calendar")return calendar(bs);
if(v==="services")return services();
if(v==="staff")return staff();
if(v==="availability")return availability();
return settings(b);
}
function stat(v,l){return `<div class="card"><div class="value">${v}</div><div class="small">${l}</div></div>`}
function bookingTable(bs){return `<div style="overflow:auto"><table><thead><tr><th>Customer</th><th>Service</th><th>Date</th><th>Staff</th><th>Payment</th><th>Status</th></tr></thead><tbody>${bs.map(x=>`<tr><td><b>${esc(x.customer_name)}</b><div class="small">${esc(x.customer_email)}</div></td><td>${esc(x.service_name)}</td><td>${esc(x.booking_date)}<br>${esc(x.booking_time)}</td><td>${esc(x.staff_name||"Team")}</td><td><span class="status ${x.payment_status==="paid"?"paid":"pending"}">${x.payment_status}</span></td><td><span class="status ${x.status}">${x.status}</span></td></tr>`).join("")}</tbody></table></div>`}
function services(){return head("Business","Services","Set prices, duration and booking buffers.",`<button class="btn primary" onclick="addService()">Add service</button>`)+`<div class="grid three">${dashboard.services.map(s=>`<div class="card"><h2>${esc(s.name)}</h2><div class="value">${money(s.price_pence)}</div><p class="muted">${s.duration} minutes · ${s.buffer} min buffer</p></div>`).join("")}</div>`}
async function addService(){const name=prompt("Service name");if(!name)return;const price=prompt("Price in £","25");const duration=prompt("Duration in minutes","60");const buffer=prompt("Buffer in minutes","10");await api("/api/services",{method:"POST",body:JSON.stringify({name,price,duration,buffer})});await loadDash();nav("services")}
function staff(){return head("Business","Staff","People who can take bookings.",`<button class="btn primary" onclick="addStaff()">Add staff</button>`)+`<div class="grid three">${dashboard.staff.map(s=>`<div class="card"><h2>${esc(s.name)}</h2><p class="muted">${esc(s.role||"Staff member")}</p><p>${esc(s.email)}</p></div>`).join("")}</div>`}
async function addStaff(){const name=prompt("Name");if(!name)return;const email=prompt("Email","");const role=prompt("Role","Staff member");await api("/api/staff",{method:"POST",body:JSON.stringify({name,email,role})});await loadDash();nav("staff")}
function availability(){const names=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];return head("Business","Availability","Set the hours customers can book.",`<button class="btn primary" onclick="saveAvailability()">Save</button>`)+`<div class="card">${names.map((n,i)=>{const a=dashboard.availability.find(x=>x.weekday===i)||{enabled:0,open_time:"09:00",close_time:"17:00"};return `<div style="display:flex;align-items:center;gap:12px;padding:12px 0;border-bottom:1px solid var(--line)"><b style="width:100px">${n}</b><input id="en${i}" type="checkbox" ${a.enabled?"checked":""}><input id="op${i}" type="time" value="${a.open_time||"09:00"}"><input id="cl${i}" type="time" value="${a.close_time||"17:00"}"></div>`}).join("")}</div>`}
async function saveAvailability(){const rows=[];for(let i=0;i<7;i++)rows.push({weekday:i,enabled:document.getElementById("en"+i).checked,open_time:document.getElementById("op"+i).value,close_time:document.getElementById("cl"+i).value});await api("/api/availability",{method:"POST",body:JSON.stringify({rows})});await loadDash();nav("availability")}
function settings(b){return head("Business","Settings","Manage your account and business profile.",`<button class="btn primary" onclick="saveBusiness()">Save</button>`)+`<div class="card"><div class="formgrid">${field("Business name","bn",b.name)}${field("Category","bc",b.category)}${field("Email","be",b.email)}${field("Phone","bp",b.phone)}<div class="field full">${field("Address","ba",b.address)}</div></div><hr><h2>Stripe</h2><div class="notice">${b.stripe_connected?"Stripe is connected. Online payments are enabled for this business.":"Stripe is not connected yet. Connect Stripe in the production onboarding flow to take payments."}</div><button class="btn dark" style="margin-top:12px" onclick="connectStripe()">Connect Stripe</button><p class="small">This demo includes the Stripe Checkout integration path. Stripe Connect onboarding should be added here for live marketplace payouts.</p></div>`}
function field(l,id,v){return `<div class="field"><label>${l}</label><input id="${id}" value="${esc(v||"")}"></div>`}
async function saveBusiness(){await api("/api/business",{method:"POST",body:JSON.stringify({name:bn.value,category:bc.value,email:be.value,phone:bp.value,address:ba.value})});await loadDash();nav("settings")}
function connectStripe(){alert("Stripe Connect onboarding is the next production step. Add a Connect OAuth/Account Link route on the server, then save the connected account ID against this business. Stripe Checkout is already wired to process payments once that connection exists.")}
function calendar(bs){let base=new Date();base.setHours(12,0,0,0);base.setDate(base.getDate()-base.getDay());let days="";for(let i=0;i<7;i++){let d=new Date(base);d.setDate(base.getDate()+i);let iso=d.toISOString().slice(0,10);days+=`<div class="day"><b>${d.toLocaleDateString("en-GB",{weekday:"short",day:"numeric"})}</b>${bs.filter(x=>x.booking_date===iso).map(x=>`<div class="event"><b>${x.booking_time}</b> ${esc(x.customer_name)}<br>${esc(x.service_name)}</div>`).join("")}</div>`}return head("Schedule","Calendar","This week's bookings.")+`<div class="card"><div class="calendar">${days}</div></div>`}
function openPublic(){const slug=dashboard.business.slug;window.open("/?book="+encodeURIComponent(slug),"_blank")}
async function publicPage(slug){publicData=await api("/api/public/"+encodeURIComponent(slug));renderPublic()}
function renderPublic(){const b=publicData.business;app.innerHTML=`<div class="public"><header class="public-head"><div class="logo">praxis<i>•</i>bookings</div><button class="btn light" onclick="loadDash()">Business login</button></header><div class="booking">${head("Book online",b.name,`${b.category} · ${b.address||""}`)}<div class="booking-grid"><div class="card"><h2>Simple online booking</h2><p class="muted">Choose a service and a convenient time.</p><div class="notice">Payments are processed securely through Stripe when this business has connected Stripe.</div></div><div class="card">${booking.step===1?serviceStep():booking.step===2?timeStep():detailsStep()}</div></div></div></div>`}
function serviceStep(){return `<h2>Choose a service</h2>${publicData.services.map(s=>`<div class="service" onclick="selectPublicService(${s.id})"><div><b>${esc(s.name)}</b><div class="small">${s.duration} mins</div></div><b>${money(s.price_pence)}</b></div>`).join("")}`}
async function selectPublicService(id){booking.service=publicData.services.find(x=>x.id===id);booking.step=2;renderPublic()}
async function timeStep(){let data=await api(`/api/public/${publicData.business.slug}/slots?service=${booking.service.id}&date=${booking.date}`);return `<h2>Choose a date & time</h2><div class="field"><label>Date</label><input type="date" min="${new Date().toISOString().slice(0,10)}" value="${booking.date}" onchange="booking.date=this.value;renderPublic()"></div><div class="times">${data.slots.map(t=>`<button class="time ${booking.time===t?"selected":""}" onclick="booking.time='${t}';renderPublic()">${t}</button>`).join("")||"<p class='muted'>No times available on this date.</p>"}</div><div style="margin-top:16px"><button class="btn light" onclick="booking.step=1;renderPublic()">Back</button>${booking.time?`<button class="btn primary" onclick="booking.step=3;renderPublic()">Continue</button>`:""}</div>`}
function detailsStep(){return `<h2>Your details</h2>${field("Full name","cn","")}${field("Email","ce","")}${field("Phone","cp","")}<div class="card" style="margin:10px 0;background:#f7f8fa"><b>${esc(booking.service.name)}</b><div class="muted">${booking.date} at ${booking.time} · ${money(booking.service.price_pence)}</div></div><button class="btn light" onclick="booking.step=2;renderPublic()">Back</button><button class="btn primary" onclick="submitPublicBooking()">Continue to payment</button>`}
async function submitPublicBooking(){try{const j=await api("/api/public/"+publicData.business.slug+"/book",{method:"POST",body:JSON.stringify({serviceId:booking.service.id,date:booking.date,time:booking.time,customerName:cn.value,customerEmail:ce.value,customerPhone:cp.value})});if(j.paymentRequired&&j.checkoutUrl)location.href=j.checkoutUrl;else{alert("Booking confirmed.");location.href="/booking-success.html?booking="+j.bookingId}}catch(e){alert(e.message)}}
async function logout(){await api("/api/auth/logout",{method:"POST"});location.reload()}
const q=new URLSearchParams(location.search);if(q.get("book")){booking={service:null,date:new Date().toISOString().slice(0,10),time:null,step:1};publicPage(q.get("book")).catch(()=>app.innerHTML="<div class='center'><div class='card'><h1>Booking page not found</h1></div></div>")}else start();
